spring:
  application:
     name: lbgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      routes:

        - id: lbservice-route

          uri: lb://USERSERVICE

          predicates:

            - Path=/users/**


        - id: lbservice2-route

          uri: lb://COURSESERVICE

          predicates:

            - Path=/courses/**

        - id: lbservice3-route

          uri: lb://ENROLMENTSERVICE

          predicates:

            - Path=/enrollments/**

        - id: lbservice4-route

          uri: lb://PROGRESSSERVICE

          predicates:

            - Path=/progress/**

        - id: lbservice5-route

          uri: lb://FEEDBACKSERVICE

          predicates:

            - Path=/feedback/**
     
     
server:
  port: 9999
  
  
management:
  endpoint:
  
    gateway:
      enabled: true
  
jwt:
  secret: your_secret_key
  expiration: 3600000
